version: "3.9"
services:
  process-sim:
    build: ./services/process-sim
    container_name: process-sim
    networks: [ proc_net ]
    ports: ["7000:7000","5020:5020"]   # REST + Modbus
  openplc:
    image: openplc/openplc:latest
    container_name: openplc
    depends_on: [ process-sim ]
    networks: [ proc_net, control_net ]
    environment:
      - MODBUS_TARGET=process-sim
  hmi:
    build: ./services/hmi
    container_name: hmi
    depends_on: [ process-sim ]
    networks: [ control_net ]
    ports: ["5000:5000"]
networks:
  proc_net: {}
  control_net: {}
