version: '3'
services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - openplc
  openplc:
    image: tuttas/openplc_v3
    ports:
      - "8080:8080"
      - "502:502"
    volumes:
      - ./plc_program.st:/app/script.st  # Mount your OpenPLC program
  # Add ICSSIM service if extending: image: your_icssim_image, etc.